/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Aluno;
import controller.DAODisciplina;
import java.util.ArrayList;
import model.Questao;

/**
 *
 * @author Avell
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    private Aluno aluno = new Aluno(0, "Bind");

    public TelaAluno() {
        initComponents();
        this.setVisible(true);
    }

    public void mainAluno(Aluno a) {
        this.lblAluno.setText("Bem vindo " + a.getNome());
        this.aluno = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();
        btnQuestoesPendentes = new javax.swing.JButton();
        btnQuestoesRespondidas = new javax.swing.JButton();
        bntDisciplina = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("3 - Responder questões Pendentes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAluno.setText("Bem vindo Aluno");

        btnQuestoesPendentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuestoesPendentes.setText("2 - Ver questões pendentes            ");
        btnQuestoesPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestoesPendentesActionPerformed(evt);
            }
        });

        btnQuestoesRespondidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuestoesRespondidas.setText("1 - Ver questões respondidas          ");
        btnQuestoesRespondidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestoesRespondidasActionPerformed(evt);
            }
        });

        bntDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntDisciplina.setText(" 4 - Ver Disciplina Atual                     ");
        bntDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDisciplinaActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgSair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAluno)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuestoesRespondidas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuestoesPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bntDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblAluno)
                .addGap(43, 43, 43)
                .addComponent(btnQuestoesRespondidas)
                .addGap(18, 18, 18)
                .addComponent(btnQuestoesPendentes)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(bntDisciplina)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQuestoesPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestoesPendentesActionPerformed
        DAODisciplina d = new DAODisciplina();
        ArrayList<Questao> questoes = new ArrayList();
        try {
            questoes = d.buscarQuestoesRespondidasAluno(d.getDisciplina("1"), this.aluno);
            questoes = d.buscarQuestoesPendentesAluno(questoes, aluno, d.getDisciplina("1"));
            TelaQuestoesPendentes tlp = new TelaQuestoesPendentes();
            tlp.preenchertable(questoes);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuestoesPendentesActionPerformed

    private void btnQuestoesRespondidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestoesRespondidasActionPerformed
        DAODisciplina d = new DAODisciplina();
        ArrayList<Questao> questoes = new ArrayList();
        try {
            questoes = d.buscarQuestoesRespondidasAluno(d.getDisciplina("1"), this.aluno);
            TelaQuestoesRespondida tlp = new TelaQuestoesRespondida();
            tlp.preenchertable(questoes);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuestoesRespondidasActionPerformed

    private void bntDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDisciplinaActionPerformed
        DAODisciplina d = new DAODisciplina();
        TelaDisciplina tl = new TelaDisciplina();
        try {
            tl.preenchertable(d.getDisciplina("1"));
        } catch (SQLException ex) {
            Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntDisciplinaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        TelaLogin tl = new TelaLogin();
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDisciplina;
    private javax.swing.JButton btnQuestoesPendentes;
    private javax.swing.JButton btnQuestoesRespondidas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAluno;
    // End of variables declaration//GEN-END:variables
}
