/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import controller.DAODisciplina;
import controller.DAOProfessor;
import model.Professor;

/**
 *
 * @author Avell
 */
public class TelaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalProfessor
     */
    private Professor p = new Professor(0, "Bind");

    public TelaProfessor() {
        initComponents();
        this.setVisible(true);
    }

    public void mainProfessor(Professor p) {

        this.lblProfessor.setText("Bem vindo Professor " + p.getNome());
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnDisciplina = new javax.swing.JButton();
        btnRespostasAlunos = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnDisciplinaAtual = new javax.swing.JButton();
        lblProfessor = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDisciplina.setText("1 - Ver todas as disciplinas");
        btnDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinaActionPerformed(evt);
            }
        });

        btnRespostasAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRespostasAlunos.setText("3 - Ver resposta dos alunos");
        btnRespostasAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostasAlunosActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrar.setText("2 - Registrar questao         ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDisciplinaAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDisciplinaAtual.setText("4 - Ver disciplina Atual         ");
        btnDisciplinaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinaAtualActionPerformed(evt);
            }
        });

        lblProfessor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProfessor.setText("Bem vindo Professor ");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgSair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblProfessor)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRespostasAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDisciplinaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addGap(33, 33, 33)
                .addComponent(lblProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnDisciplina)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btnRespostasAlunos)
                .addGap(18, 18, 18)
                .addComponent(btnDisciplinaAtual)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinaActionPerformed
        DAOProfessor pro = new DAOProfessor();
        TelaDisciplinaProfessor tl = new TelaDisciplinaProfessor();
        try {

            tl.preencherTable(pro.getDisciplinas(this.p));
        } catch (SQLException ex) {
            Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisciplinaActionPerformed

    private void btnRespostasAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostasAlunosActionPerformed
        DAODisciplina d = new DAODisciplina();
        TelaQuestoesRespondidasProfessor tl = new TelaQuestoesRespondidasProfessor();
        try {
            tl.preenchertable(d.buscarQuestoesRespondidasProfessor(d.getDisciplina("1")));
        } catch (SQLException ex) {
            Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRespostasAlunosActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        DAODisciplina d = new DAODisciplina();
        TelaFazerQuestao tl = new TelaFazerQuestao();
        try {
            tl.pegarDados(d.getDisciplina("1"));
        } catch (SQLException ex) {
            Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnDisciplinaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinaAtualActionPerformed
        DAODisciplina d = new DAODisciplina();
        TelaDisciplina tl = new TelaDisciplina();
        try {
            tl.preenchertable(d.getDisciplina("1"));
        } catch (SQLException ex) {
            Logger.getLogger(TelaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisciplinaAtualActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        TelaLogin tl = new TelaLogin();
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisciplina;
    private javax.swing.JButton btnDisciplinaAtual;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRespostasAlunos;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblProfessor;
    // End of variables declaration//GEN-END:variables
}
