/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAOAlternativa;
import controller.DAODisciplina;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Alternativa;
import model.Aluno;
import model.Questao;

/**
 *
 * @author Avell
 */
public class TelaResponderQuestao extends javax.swing.JFrame {

    /**
     * Creates new form TelaResponderQuestao
     */
    public TelaResponderQuestao() {
        initComponents();
        this.setVisible(true);
    }
    Questao q = new Questao();
    Aluno aluno;

    public void preencherDados(Questao q, Aluno a) {
        this.aluno = a;
        this.q = q;
        this.txtQuestao.setText(q.getDesc());
        DefaultTableModel modelo = (DefaultTableModel) this.tlbAlternativas.getModel();
        Iterator<Alternativa> perc = q.alternativas.iterator();
        while (perc.hasNext()) {
            Alternativa tmp = perc.next();
            modelo.addRow(new Object[]{
                tmp.getId(),
                tmp.getDesc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQuestao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbAlternativas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnResponder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Questão:");

        tlbAlternativas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Alternativa"
            }
        ));
        jScrollPane1.setViewportView(tlbAlternativas);

        jLabel2.setText("Id:");

        btnResponder.setText("Responder");
        btnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnResponder)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                        .addComponent(txtId)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnResponder)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderActionPerformed
        boolean b = false;
        int numb = 0;
        try {
            numb = Integer.parseInt(this.txtId.getText());
            b = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um numero");
            this.txtId.setText("");
        }

        if (b) {
            boolean aux = false;
            Iterator<Alternativa> p = this.q.alternativas.iterator();
            while (p.hasNext()) {
                Alternativa tmp = p.next();
                if (numb == Integer.parseInt(tmp.getId())) {
                    TelaResponderQuestao tl = new TelaResponderQuestao();
                    DAODisciplina dd = new DAODisciplina();
                    try {
                        System.out.println(this.aluno.getId() + "Chegou ");
                        dd.responderQuestao(this.aluno, q, tmp);
                        this.dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaResponderQuestao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.dispose();
                    aux = true;
                    break;
                }
            }
            if (aux == false) {
                JOptionPane.showMessageDialog(null, "Digite um Id Válido");
            }
        }
    }//GEN-LAST:event_btnResponderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResponder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbAlternativas;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtQuestao;
    // End of variables declaration//GEN-END:variables
}
