/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAODisciplina;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Alternativa;
import model.Disciplina;
import model.Questao;

/**
 *
 * @author Avell
 */
public class TelaFazerQuestao extends javax.swing.JFrame {

    private Questao q = new Questao();
    private Disciplina d = new Disciplina();
    private int cont = 0;

    /**
     * Creates new form TelaFazerQuestao
     */
    public TelaFazerQuestao() {
        initComponents();
        this.setVisible(true);
    }

    public void pegarDados(Disciplina d) {
        this.d = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDesc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cCorreta = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Questao:");

        txtQuestao.setColumns(20);
        txtQuestao.setRows(5);
        jScrollPane1.setViewportView(txtQuestao);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Alternativas:");

        tblDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Descrição", "Correta"
            }
        ));
        jScrollPane2.setViewportView(tblDesc);

        jLabel3.setText("Descrição:");

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cCorreta.setText("Correta");
        cCorreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCorretaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Registro de Questões");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtDesc)
                                    .addGap(18, 18, 18)
                                    .addComponent(cCorreta)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnAdd)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(cCorreta))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tblDesc.getModel();
        if (this.cCorreta.isSelected() == false) {

            Alternativa a = new Alternativa(null, this.txtDesc.getText(), this.cCorreta.isSelected());
            this.q.alternativas.add(a);
            modelo.addRow(new Object[]{
                this.txtDesc.getText(),
                this.cCorreta.isSelected()
            });
            this.txtDesc.setText("");
            this.cCorreta.setSelected(false);
        } else if (this.cCorreta.isSelected() && cont == 0) {
            this.cont = 7;
            Alternativa a = new Alternativa(null, this.txtDesc.getText(), this.cCorreta.isSelected());
            this.q.alternativas.add(a);
            modelo.addRow(new Object[]{
                this.txtDesc.getText(),
                this.cCorreta.isSelected()
            });
            this.txtDesc.setText("");
            this.cCorreta.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(null, "Apenas  uma alternativa deve ser correta");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cCorretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCorretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCorretaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!"".equals(this.txtQuestao.getText())) {
            if (this.cont != 0) {
                if (this.q.alternativas.size() >= 2) {
                    DAODisciplina dd = new DAODisciplina();
                    try {
                        this.q.setId_disciplina(this.d.getId());
                        this.q.setDesc(txtQuestao.getText());
                        dd.registrarQuestao(this.d, this.q);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Questao Registrada com Sucesso");
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaFazerQuestao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Uma pergunta deve ter no minimo 2 alternativas");
                }
            } else {
                JOptionPane.showMessageDialog(null, "A questão precisa ter no minimo uma alternativa correta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "A questao deve ter uma descrição");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cCorreta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDesc;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextArea txtQuestao;
    // End of variables declaration//GEN-END:variables
}
